export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CONTACTS_LOADING = 'CONTACTS_LOADING';
export const CONTACTS_LOAD_SUCCESS = 'CONTACTS_SUCCESS';
export const CONTACTS_LOAD_ERROR = 'CONTACTS_ERROR';
export const LOGOUT_USER ='LOGOUT_USER';